const express = require("express")
const mongoose = require("mongoose")
const dotenv = require("dotenv")
const cors = require("cors")

const Station = require("./models/Station")
const routes = require("./routes")

dotenv.config()

const app = express()
const port = process.env.PORT || 3000

// Middleware
app.use(cors())
app.use(express.json())

// MongoDB Connection
const MONGODB_URI =
  process.env.MONGODB_URI || "mongodb://localhost:27017/zpetrolapp"

mongoose
  .connect(MONGODB_URI)
  .then(() => console.log("MongoDB connected successfully!"))
  .catch(err => console.error("MongoDB connection error:", err))

/*========================================
 * Data for Seeding (Copied from Services.jsx)
 * This data can be moved to a separate file if it gets very large.
 *========================================*/
const rawStationsData = [
  {
    name: "Z 11th Ave",
    address: "Cnr Eleventh Avenue and Cameron Road, Tauranga",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z 15th Ave",
    address: "10-18 Fifteenth Avenue, Tauranga",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Addington",
    address: "250 Lincoln Road, Addington, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Albany",
    address: "287 Oteha Valley Road, Albany",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Andy Bay",
    address: "333 Andersons Bay Road, Andy Bay, Dunedin",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Avondale",
    address: "50-60 Ash Street, Avondale, West Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Barrington",
    address: "253 Barrington Street, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Belfast",
    address: "Cnr Main North Road and Johns Road, Belfast",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Bethlehem",
    address: "253B State Highway 2",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Bishopdale",
    address: "210 Harewood Road, Bishopdale, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Botany Downs",
    address: "550 Te Irirangi Drive, Botany Downs, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Broadway",
    address: "Cnr Calabar Rd and Broadway, Strathmore",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Brougham St",
    address: "495 Brougham Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Browns Rd",
    address: "270 Roscommon Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Bryndwr",
    address: "52 Strowan Road, Bryndwr, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Cambridge",
    address: "81 Victoria Street, Cambridge",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Carlton Corner",
    address: "1 Papanui Road, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Caroline Bay",
    address: "62 Theodosia Street, Timaru",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Cashmere",
    address: "23-25 Colombo Street, Beckenham, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Central Parade",
    address: "500 Maunganui Road, Mount Maunganui",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Clevedon",
    address: "24-28 Papakura-Clevedon Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Constable St",
    address: "35 Constable St, Newtown, Wellington",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Huatoki (Z Courtenay Street)",
    address: "Cnr Courtenay Street and Liardet Street, New Plymouth",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Curletts Rd",
    address: "Cnr Curletts Road and Blenheim Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Tuhikaramea (Z Dinsdale)",
    address: "Cnr Whatawhata Road and Tuhikaramea Road, Dinsdale, Hamilton",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Dublin St",
    address: "14 Dublin Street, Whanganui",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Ellerslie",
    address: "301 Ellerslie-Panmure Highway, Mt Wellington, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Fenton St",
    address: "Cnr Fenton and Victoria Street, Rotorua",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Te Papanui (Z Five Cross Roads)",
    address: "243 Peachgrove Road, Enderley, Hamilton",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Frankton",
    address: "Cnr Lincoln and Edgar Streets, Frankton, Hamilton",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Geraldine",
    address: "Cnr Waihi Terrace & Pine Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Gladstone",
    address: "455 Dee Street, Invercargill",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Glen Innes",
    address: "222-236 Apirana Avenue, Glen Innes, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Glen Park",
    address: "241 Glenfield Road, Hillcrest, North Shore",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Green Bay",
    address: "82 Godley Road, Green Bay, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Green Island",
    address: "185 Main South Road, Green Island, Dunedin",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Greenlane",
    address: "128 Greenlane Road, Greenlane, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Hautapu",
    address: "167 Victoria Road, Cambridge, New Zealand",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Havelock Nth",
    address: "Cnr Havelock Road and Porter Drive, Havelock North",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Henderson Valley",
    address: "1 Corban Avenue, Henderson, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Heretaunga St",
    address: "Cnr Heretaunga Street West and Southland Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z High Street",
    address: "834 High Street, Boulcott, Lower Hutt",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Hunters Corner",
    address: "72-76 East Tamaki Road, Papatoetoe, South Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Huntly",
    address: "390 Great South Road, Huntly",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Hutt Rd",
    address: "453 Hutt Road, Lower Hutt",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Inglewood",
    address: "47 Rata Street, Inglewood",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Johnsonville",
    address: "136-140 Johnsonville Road, Johnsonville, Wellington",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kahikatea Drive",
    address: "124-126 Kahikatea Drive, Hamilton",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kaikohe",
    address: "Broadway, Kaikohe",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kaitaia",
    address: "141-145 Commerce Street, Kaitaia",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kamo",
    address: "382 Kamo Road, Whangarei",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kapiti",
    address: "Cnr Kapiti Road and Milne Drive, Paraparaumu",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Karamu Rd",
    address: "927 Karamu Road North",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kawerau",
    address: "6 Islington Street, Kawerau",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kennedy Rd",
    address: "Cnr Tennyson Street & Station Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kensington",
    address: "Cnr Kamo Rd and Nixon Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kepa Rd",
    address: "154 Kepa Road, Orakei, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kilbirnie",
    address: "16-22 Coutts Street, Kilbirnie, Wellington",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kingsway",
    address: "26 Clevedon Road, Papakura",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Kumeu",
    address: "134-152 Main Road, State Highway 16",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Lakeside",
    address: "Cnr Northcote Road and Taharoto Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Lincoln Rd",
    address: "198 Lincoln Road, Henderson",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Linwood",
    address: "Cnr Linwood Avenue and Cashel Street, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z London St",
    address: "171 London St & Cnr Glasgow St",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Mana",
    address: "143 Mana Esplanade",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Manurewa",
    address: "1 Alfriston Road, Manurewa, South Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Marton",
    address: "166 Broadway, Marton",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Matamata",
    address: "Cnr Waharoa Road and Peria Road, Matamata",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Merrilands",
    address: "202 Mangorei Road, New Plymouth",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Miramar",
    address: "27 Miramar Avenue, Miramar, Wellington",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Moorhouse",
    address: "40 Moorhouse Avenue, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Morrinsville",
    address: "202-210 Thames Street, Morrinsville",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Mosgiel",
    address: "Cnr Gladstone Road and Quarry Road, Mosgiel",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Mungavin Ave",
    address: "1-5 Mungavin Avenue, Porirua East, Wellington",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z New Lynn",
    address: "62 Rata Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Northcote",
    address: "119 Onewa Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Northcross",
    address: "847-849 East Coast Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Ormiston Rd",
    address: "8 Ormiston Road, Flat Bush, South Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Otahuhu",
    address: "19 Princes Street, Otahuhu, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Pakuranga",
    address: "470 Pakuranga Highway, Pakuranga, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Palm Beach",
    address: "16 Domain Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Palmerston",
    address: "112 Ronaldsay Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Papakura North",
    address: "254 Great South Road, Takanini, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Picton",
    address: "101 High Street, Picton",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Pioneer Hwy",
    address: "676 Pioneer Highway",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Point Chev",
    address: "1125-1143 Great North Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Ponsonby",
    address: "5-9 Williamson Avenue",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Pukekohe",
    address: "11 Stadium Drive",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Pukete",
    address: "Cnr Pukete and Te Rapa Roads, Te Rapa, Hamilton",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Putaruru",
    address: "68-70 Tirau Street, Putaruru",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Queenstown",
    address: "846 Frankton Road, Queenstown",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Redwood",
    address: "225 Scott Street, Blenheim",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Rotokauri",
    address: "Cnr Wairere Drive & Arthur Porter Drive",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Royal Oak",
    address: "700 Mount Albert Road, Royal Oak, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Rutherford",
    address: "106 Rutherford Street, Nelson",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Sawyers Arms",
    address: "530 Sawyers Arms Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Shirley",
    address: "7 Marshland Road, Shirley, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Silverdale",
    address: "5 Hibiscus Coast Highway",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Springlands",
    address: "165 Middle Renwick Road, Blenheim",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Stadium",
    address: "26 Mill Street, Hamilton",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Stoke",
    address: "666 Main Road, Stoke, Nelson",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Stratford",
    address: "Cnr Broadway and Regan Street, Stratford",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Sunnybrae",
    address: "37 Northcote Road, Takapuna",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Taipa",
    address: "570 State Highway 10",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Tamatea",
    address: "6 Durham Avenue, Tamatea",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Taradale",
    address: "21 Lee Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Taranaki St",
    address: "155 Taranaki Street, Wellington",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Tauhara",
    address: "200 Napier-Taupo Rd, Hilltop, Taupo",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Tawa",
    address: "16-18 Main Road, Tawa, Wellington",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Te Atatu",
    address: "402 Te Atatu Road, Te Atatu, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Te Awamutu",
    address: "601 Sloane Street, Te Awamutu",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Te Irirangi Dr",
    address: "136 Dawson Road, Otara, South Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Te Puke",
    address: "Cnr Jellicoe Street and King Street, Te Puke",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Terrace End",
    address: "768 Main Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Ti Rakau Dr",
    address: "284 Ti Rakau Drive, East Tamaki, South Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Tom Pearce Dr",
    address: "Tom Pearce Drive, Auckland International Airport",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Trentham",
    address: "430 Fergusson Drive, Trentham, Upper Hutt",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Valley",
    address: "248 Kaikorai Valley Road, Kaikorai, Dunedin",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z VIC Corner",
    address: "545-555 High Street, Lower Hutt",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Vivian St",
    address: "174 Vivian St, Wellington",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Waikuku",
    address: "1413 Main North Road, Waikuku",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Waikumete",
    address: "4155 Great North Road, Glen Eden, Auckland",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Waiuku",
    address: "16 Kitchener Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Warkworth",
    address: "1 Hudson Road, Warkworth",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Whakatane",
    address: "Cnr Domain Road and King Street, Whakatane",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Whangaparaoa",
    address: "651 Whangaparaoa Road, Whangaparaoa",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Whitianga",
    address: "83-85 Albert Street, Whitianga",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Windsor",
    address: "701 Heretaunga St East",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Wiri Station Rd",
    address: "83 Wiri Station Road, Manukau City",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Woolston",
    address: "417 Ferry Road, Christchurch",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Karaka",
    address: "47 Harbourside Drive, Karaka, Auckland 2113",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Amberley",
    address: "47 Carters Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Ashburton",
    address: "141 West Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Awakeri",
    address: "RD2, Whakatane",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Balclutha",
    address: "High Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Beach Rd",
    address: "150 Beach Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Constellation Dr",
    address: "36 Constellation Drive",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Cromwell",
    address: "Cnr Barry Avenue and Murray Terrace",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Dee St",
    address: "206-214 Dee Street, Invercargill",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Fairy Springs",
    address: "23 Fairy Springs Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Gisborne service station",
    address: "300 Gladstone Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Gore",
    address: "Corner Hokonui Drive & Irwell Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Greymouth",
    address: "10 Whall Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Grove Rd",
    address: "Corner Grove Road & Budge Street",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
  {
    name: "Z Harris Rd",
    address: "142 Harris Road",
    services: [
      "24/7 Pay at Pump",
      "Pay in App",
      "Z Espress Coffee & Fresh Food",
      "Z2O Carwash",
      "Trailer Hire",
      "LPG SWAP'n'GO",
      "Bathrooms",
    ],
  },
]

/*========================================
 * Routes
 *========================================*/

// Basic API Route
app.get("/", (req, res) => {
  res.send("Backend is running!")
})

// Seeding route
app.post("/api/seed-stations", async (req, res) => {
  try {
    await Station.deleteMany({})
    console.log("Existing stations cleared.")

    // Prepare data to include the 'town' field
    const stationsToInsert = rawStationsData.map(station => {
      const parts = station.address.split(",").map(part => part.trim())
      const town = parts.length > 1 ? parts[parts.length - 1] : ""
      return { ...station, town }
    })

    const result = await Station.insertMany(stationsToInsert)
    res
      .status(200)
      .json({ message: "Stations seeded successfully!", count: result.length })
  } catch (error) {
    console.error("Error seeding stations:", error)
    res
      .status(500)
      .json({ message: "Error seeding stations", error: error.message })
  }
})

// Route to get all stations
app.get("/api/stations", async (req, res) => {
  try {
    const stations = await Station.find({})
    res.status(200).json(stations)
  } catch (error) {
    console.error("Error fetching stations:", error)
    res
      .status(500)
      .json({ message: "Error fetching stations", error: error.message })
  }
})

// Routes
app.use("/api/stations", routes.stationFuelPriceRoutes)

// Start the server
app.listen(port, () => {
  console.log(`Backend server listening on port ${port}`)
})
